# https://dev.to/michi/publish-to-npm-automatically-with-github-actions-5805
name: Publish Node Package

on:
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # "ref" specifies the branch to check out.
          # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
          ref: ${{ github.event.release.target_commitish }}
     
      - name: Use Node.js 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          # Specifies the registry, this field is required!
          # registry-url: https://registry.npmjs.org/
          registry-url: 'https://npm.pkg.github.com'
          scope: '@melenaos'

      # clean install of your projects' deps. We use "npm ci" to avoid package lock changes
      - name: Install dependencies
        # Skip post-install scripts here, as a malicious script could steal NODE_AUTH_TOKEN.
        run: "npm ci --ignore-scripts"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
      # set up git since we will later push to the repo
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "CI@menelabs.com"
      # upgrade npm version in package.json to the tag used in the release.
      - run: npm version ${{ github.event.release.tag_name }}
      # build the project
      - run: npm run build
      # run tests just in case
      - run: npm run test:prod
      # publish to NPM -> there is one caveat, continue reading for the fix
      # Change the followin line to this \/-- if you want to get a v1,v2,v3 version.
      # now it will publish the latest to the last published package.
      # - run: npm publish --tag ${{ github.event.release.target_commitish }}
      - run: npm publish
        env:
          # Use a token to publish to NPM. See below for how to set it up
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # push the version changes to GitHub
      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
